### PR TITLE
Issue #248 RectMapCollider, player sometimes stuck

### PR DESCRIPTION
**Pull request by dangillet**
Hello,

I've been thinking a bit about this problem. I'm sure physic engines have excellent solutions. Here is what I came up with. The basic idea is to say that for each cell we collide with, we only want to correct the new rect by the shortest distance possible. So if we find that we need to move it by 4 px in the X and by 2 px in the Y, we only move it by 2 px in the Y.
Now the only problem that is left is if we are positioned exactly on the diagonal and we find out that we should be moved by the same amount on the X and Y axis. In this case, we first don't correct anything with this cell, but we mark it with a special flag. We will come back to this cell after resolving all the other collisions. So we give the opportunity to the other cells which don't have this special positioning (being on the diagonal) to correct the new rect position correctly.

Once we're done with the collision resolutions, we take all the cells that were flagged, and we now see if we're still in the same situation. The situation might have changed if there were other cells which corrected the new rect position. 
But if are are still in the same situation, we now choose to move the new rect on both X and Y axis. We could have chosen an arbitrary axis instead.

Here is a proposition of this method.

Regards,
Daniel.

### CODE REVIEW

**Comment by dangillet** [comment]
Thanks to your tests, it appeared that is was actually required to first consider the collisions where displacement on only one axis is required. So I changed the code accordingly.

There are still 2 tests which fail. But I think the test itself is wrong. They both exhibit the same *problem*.

As an example, I'll take the first test 
```python
________________________ TestClass.test_no_stuck[115] _________________________

self = <test_RectMapCollider__no_stuck.TestClass object at 0x03399390>
generic_id = "('diagonal_gap_2v', 'up_right', (2, 2), (0, 1))"
tilemap = <cocos.tiles.RectMap object at 0x03327550>
start_rect = Rect(xy=4,6; wh=8,6), dx = 2, dy = 3, expect_dxdy = (0, 3)

    def test_no_stuck(self, generic_id, tilemap, start_rect, dx, dy, expect_dxdy):
        collider = RectMapCollider()
        new = start_rect.copy()
        new.x += dx
        new.y += dy
        new_dx, new_dy = collider.collide_map(tilemap, start_rect, new, dy, dx)
>       assert new.position == (start_rect.x + expect_dxdy[0],
                                start_rect.y + expect_dxdy[1])
E       assert (6, 9) == (4, 9)
E         At index 0 diff: 6 != 4
E         Use -v to get the full diff

test_RectMapCollider__no_stuck.py:125: AssertionError
```
The map looks like this (I added `P` to show the player starting position)
```python
    'diagonal_gap_2v':    ( "o o o o o" +
                            "o o o o o" +
                            "x P P o o" +
                            "o P P x o" +
                            "o o o o o" +
                            "o o o o o" ),
```
The test tries to move the player up_right for a distance (2, 3). But the height of the tiles are 3. So the player would actually end up exactly above the tile to his right. So between the starting position and arrival position, the rects do not collide with the tile. This is called tunneling. Physics engines like Box2D would solve this by using *continuous collision detection* (see [doc](http://www.box2d.org/manual.html) under **Bullet**). But I don't think it's the goal for cocos2d to provide such an elaborate collision response. We should just make sure the player is not moving so fast that he could in one frame go through an entire tile. 

Note that the test passes for a movement of (3, 2).

The tests could be changed by increasing  a bit the tiles size compared to the player dx, dy.

Let me know what you think.

Daniel.

**Comment by ccanepa** [comment]
Good catch.
You can confirm by changing in the test the expansion of dx, dy from [(2,3), (3,2)] to [(3,2), (1,2)] and re-running the test

**Comment by ccanepa** [comment]
Ok, I fixed the  false failures that you pointed above, and now your branch pases all the tests. (please rebase on master)

On the review:
First two stylistical  ones

`1.` you are using the pattern
```
# comment about the true block in an if
if ....:
   ...
# comment about the else block in an if
else:
  ...
```

In general is considered better written as
```
if ....:
   # comment about the true block in an if
   ...

else:
   # comment about the else block in an if
  ...
```

on the basis that if reverting the condition in the if there are better probabilities that the comments will be seen and adjusted


`2.` If 'a' is known to have a boolean value, then `if a is True:` looks redundant; use `if a:` 
  (I'n reference to lines like `if getattr(cell, 'collide_later', False) is True:` )
 

A minor comment on performance:
`3.` When evaluating bool(getattr(cell, 'collide_later', False)), python first look if the attr exists and the evaluates as bool; in those 'if' mentioned above, we know 'attr exist'  implies it is True, so `if getattr(...):` is equivalent to `if hasattr(cell, 'collide_later')` and python does not need to evaluate the value. It is a very small gain per bool evaluation [ 4% in py27, 2.5% in py33] but is free


`4.`   in method collide_map theres the block
```python
        for cell in cells_collide_later:
            if not cell.intersects(new):
                continue
            dx, dy = self.do_collision(cell, last, new, dy, dx)
        for cell in cells_collide_later:
            del cell.collide_later

``` 
Theres probably a very small gain in performance, and maybe in clarity if rearanged in one loop:
```python
        for cell in cells_collide_later:
            if cell.intersects(new):
                dx, dy = self.do_collision(cell, last, new, dy, dx)
            del cell.collide_later

```
 
`5.` function / method calls are costly in python. I wonder if things can be refactored so inlining _collision_resolution_x  and _collision_resolution_y 
* does not produce code repetitions
* code remains legible

The relevant current code in your branch is
```python
        # Correction on both axis
        if dx_correction != 0. and dy_correction != 0.:
            if getattr(cell, 'collide_later', False) is True:
                if abs(dx_correction) < abs(dy_correction):
                    dx = self._collision_resolution_x(new, dx, dx_correction)
                elif abs(dy_correction) < abs(dx_correction):
                    dy = self._collision_resolution_y(new, dy, dy_correction)
                # Same distance on both axis
                else:
                    dx = self._collision_resolution_x(new, dx, dx_correction)
                    dy = self._collision_resolution_y(new, dy, dy_correction)
            else:
                cell.collide_later = True
        # Correction on X axis only
        elif dx_correction != 0.:
            dx = self._collision_resolution_x(new, dx, dx_correction)
        # Correction on Y axis only
        elif dy_correction != 0.:
            dy = self._collision_resolution_y(new, dy, dy_correction)
        return dx, dy

```

To not repeat, the active calls must must be the last in the block, so the elif must be changed to 'if' to have a chance to execute, and then look to modify the block above so the actions performed are equivalent.
I got this:

```python
        # Correction on both axis
        if dx_correction != 0. and dy_correction != 0.:
            if getattr(cell, 'collide_later', False) is True:
                if abs(dx_correction) < abs(dy_correction):
                    # do correction only on x (below)
                    dy = 0.0
                elif abs(dy_correction) < abs(dx_correction):
                    # do correction only on y (below)
                    dx = 0.0
                # Same distance on both axis
                else:
                    # let both corrections happen below
                    pass
            else:
                # correct nothing in this round
                cell.collide_later = True
                return dx, dy
        # Correction on X axis only
        if dx_correction != 0.:
            dx = self._collision_resolution_x(new, dx, dx_correction)
        # Correction on Y axis only
        if dy_correction != 0.:
            dy = self._collision_resolution_y(new, dy, dy_correction)
        return dx, dy

```
now the _collision... can be inlined
I don't see much lose in readability and malleability, but it's your call

`6.` I'm not sure about the change in Rect, will think about it and comment later

`7.` I don't want to consider TmxObjectMapCollider now, will think about it and comment later

**Comment by dangillet** [comment]
Thanks for the code review! I made all the changes you suggested. They all made sense. I especially like the inlining of the functions `_collision_resolution_`. I rebased on master and squashed my commits. The Travis CI build fails but that's because of *test_RectMapCollider__no_stuck - copia.py*. I locally fixed the problems by moving line 60 `from cocos.sprite import Sprite` to line 365 (in the __main__ if we did not set `cocos_utest`). Also there is a typo in the function `generate_maps`. `tile_filled` is missing an **l**.

For the tests themselves, I noticed one small thing. It's only a little performance thing, and I'm not even sure it matters that much. You write
```python
    'empty':              ( "o o o o o" +
                            "o o o o o" +
                            "o o o o o" +
                            "o o o o o" +
                            "o o o o o" +
                            "o o o o o" ),
```
You can remove all the *+* signs like this:
```python
    'empty':              ( "o o o o o"
                            "o o o o o"
                            "o o o o o"
                            "o o o o o"
                            "o o o o o"
                            "o o o o o" ),
```
The advantage is that python does not create several strings and then starts to add them one by one. The interpreter sees immediately that this is only one string and allocates only that string.

Regarding point `6.` here is how I see it. Consider that the positions are only integers. So you can only place Rects at positions like (0, 0) (1, 0), etc... The locations are actually like a grid. If you place a Rect in the location (0, 0), it fills this entire square in the grid and nothing else. We can say that its witdh and height are 1, because you count 1 square. If you have a Rect at location (0, 0) with a width and height of 10, 10, then the topright corner will be at location (9, 9). It's like 0-based indexing. If I want to place another Rect besides this Rect, I will need to place it at location (10, 0). If I go at 9, it overlaps.

Now if you relax the assumption that positions are only integers, but can be floats, for a Rect of size 1, 1, its topright corner will be located at (0.999999999, 0.9999999999) with as many 9s as you can put. With floats, if we have an epsilon, we could say it's at location (1-espilon, 1-epsilon). But this is so close to 1 that it makes everything easier to accept that the borders of the Rect occupies the location (1, 1). But its content does not. So filling a grid with Rects would means that they share their borders, but they do not intersect.


I have a question while we're changing `collide_map(self, map, last, new, dy, dx)`. Why on earth do we pass `dy, dx` in that order but receive `dx, dy` as returned values ?? Wouldn't it make more sense to just have ``collide_map(self, map, last, new, dx, dy)` ?

Also in that function, there is this `set` of tested cells. But what is it used for ?? As a previous comment suggested 

>     # resolve them and re-collide if necessary; make sure the cells
    # colliding the sprite midpoints are done first

There was probably such a check and when re-colliding they were making sure the cell was not yet tested. But now this is not the case anymore. I'm using it to find the cells which have the attribute `collide_later`. So I could keep that, but the check below seems unnecessary.
```python
            if cell in tested:
                # don't re-test
                continue
````
I tried removing it and all tests pass.

Daniel.

**Comment by ccanepa** [comment]
Re-review:
 `1.` After inlining, the methods _collision_resolution_* are not more used, so they can be deleted

`2.` Don't do cleanup or api changes at this point, see reasons below [X]

`3.` The docstring in Rect.intersects should be changed to match the new behavior (before it was ..any overlay, now it is any interior point overlaps). Phrase as you like.

`4.` Edit changelog by adding one line for each notable change. Mark changes in api by preceding with an '*' so at release time we can warn users; after merging in master the hash with the commit that changed the api will be added

By example, I would put something as
```
fixed RectMapCollider stuck sometimes, #238
* Rect.intersects behavior change: now points in border not count, only interior ones
````

With those changes things are ready to land in master,  albeit not directly.

[X] Sometimes a change in the library breaks third party code, or even other library's parts.
To fix that one usually goes back in time and find the commit n such that with commit n the problematic code works and with n+1 does not.
Then examine the diff between n+1 and n to understand the problem.
This is easier with small diffs, and if the commit does not mix different features.

With that in mind, I would put the changes for #238 as four commits
*   deleted unwanted test file [ deleting test_RectMapCollider__no_stuck - copia.py] 
*   fixing RectMapCollider stuck sometimes, #248 [ Here the changes in Rect and RectMapCollider, don't change  TmxObjectMapCollider]
*   cleanup RectMapCollider   [ here the cleanups deemed necessary ]
* API change: RectMapCollider .do_collision and collide_map now receive dx,dy instead of dy,dx

The most easier way to do that would be

1. Make the changes 1-4 mentioned above in your branch; don't bother rebasing
2. clone los-cocos/master as a separate repo
3. delete utest/test_RectMapCollider__no_stuck - copia.py, commit to master
4. copy paste the changes in Rect and RectMapCollider from your branch to master; copy changelog, commit to master
5. Do cleanup in your branch, not changing the api. If unsure, post here for review. Copy cleanup changes from your branch to master, commit to master
6. Change the api (dy,dx -> dx, dy) , add a line in changelog about the api change. Commit to master

Then will be the time to close the issue: 
* move things mentioned here but not addressed by the commits to new issue(s) [the Tmx collider] 
* add a final post to this issue with "fixed by commit hashstring_of _second_commit" , mention additional issues created
* close the issue

**Comment by dangillet** [comment]
Hi Claudio,

I made all the necessary changed in my branch.
I cloned cocos and deleted the unwanted test. I did not yet pushed my changes.
I'm about to copy-paste the changes from my branch to master. But I want to make sure I understand something. What do you call code cleanup? Is it the part about the string concatenation in the tests ? Is it more than that, like deleting the part about the set of tested cells ?

For the changelog itself, I'm unsure about the formatting you are expecting. Is this ok?
```
- fixed RectMapCollider stuck sometimes, #238
- * Rect.intersects behavior change: now points on border do not count, only interior ones
```

I'll wait for your comments before going further.

**Comment by ccanepa** [comment]
> What do you call code cleanup? Is it the part about the string concatenation in the tests ? Is it more than that, like deleting the part about the set of tested cells ?

I  was thinking like the second, but you can also change the tests if you want. You can also delete the line `self.resting = False` that does nothing.

**Comment by dangillet** [comment]
So I pushed my first two commits. I'm now busy with #3 Code cleanup. I'm using this pullrequest to let you see what has been done. Actually not much... Which is why I'm wondering if I'm doing this correctly.

If this is all fine, I'll copy the changes back to the repo and will make a new commit. Then we will still have the API change to do, and I'll then open a new issue for `TmxObjectMapCollider`.

Thanks for your guidance!

**Comment by ccanepa** [comment]
Not seeing your master I'm not totally sure, but probably is ok; I assume your commits in master are:
* 1st commit: delete unwanted test
* 2nd: master state matches your branch commit 6c8917ce9
* 3rd: master state matches your branch commit 32829cd125

**Comment by dangillet** [comment]
* 1st commit: delete unwanted test is already pushed here on master. [c9c70d1](https://github.com/los-cocos/cocos/commit/c9c70d16f9f95f018af7b3cb51ee71f75efea3bc)
* 2nd commit: copy paste the changes in Rect and RectMapCollider from your branch to master; copy changelog, commit to master. That is also pushed here on master [fcf5fd0](https://github.com/los-cocos/cocos/commit/fcf5fd0bf890fc222ab5e08473b12de38aa2e354)
* 3rd: Code cleanup. This is found in my pull request. I've rebase my branch onto los-cocos/master. The commit for cleanup can be found here: [32829cd](https://github.com/dangillet/cocos/commit/32829cd12543a814917f1ac77c4db61cdad4d069)

I'm waiting for your ok so that I can copy these changes onto master and push them.
When this is done, I'll tackle the API change (invert dy, tx to dx, dy)

**Comment by ccanepa** [comment]
looks right, go ahead

**Comment by dangillet** [comment]
I went ahead and pushed the changes. I've also created a new branch https://github.com/los-cocos/cocos/tree/api_changes to make sure the API changes are ok. If so, I will merge them back into master and delete this temporary branch.

Daniel.

**Comment by ccanepa** [comment]
Thats the change in the library as was talked, but you should adjust as necessary the calls to those methods elsewhere in the repo.

A search from the repo top dir for .collide_map and .do_collision should give at least
test/platformer.py
utest\test_RectMapCollider__no_stuck.py
utest\viewer_RectMapCollider__no_stuck.py

It probably will be clearer if the api change and the adjust ends in the same commit to master

**Comment by dangillet** [comment]
Hi Claudio,

Thanks for spotting this! I was looking into the test folder but could not find anything. It's indeed much smarter to search for those methode names. I need to better use grep tool. ;)

I amended the commit in the api_changes branch and force pushed it. Let me know if it's good to merge back to master.

If so, I'll close this ticket as you explained, and will open a new one for TmxMapCollider.

**Comment by ccanepa** [comment]
fine, go ahead

**Comment by dangillet** [comment]
Closing this pullrequest as the issue has been fixed.

**Pull request closed without merging**
