### PR TITLE
This PR normalises the line endings in the repository

### PR DESCRIPTION
**Pull request by r1chardj0n3s**
The cocos repository has a wildly varying mixture of line endings, including mixtures inside individual files. This patch normalises the line endings and also configures git to normalise in the future.

### CODE REVIEW

**Comment by ccanepa** [comment]
- fresh checkout of master, which has an eol correction: git status gives locally changed files all py.
- trying to checkout this remote branch, gives 'local changes, stash ...'
- stashing and trying to checkout gives 'local changes, stash'
- all this on windows

So I will merge this to see if the repo goes to a better state; if anything fails we can correct later.

will check results later, probably tomorrow

**Comment by ccanepa** [comment]
Ok, the new master checks out clean.
After changing alternate lines in cocosnode.py to CRLF

```
E:\_\cocos_pristine\cocos2017\cocos>git status cocosnode.py
On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   cocosnode.py

no changes added to commit (use "git add" and/or "git commit -a")

E:\_\cocos_pristine\cocos2017\cocos>git diff cocosnode.py
warning: CRLF will be replaced by LF in cocos/cocosnode.py.
The file will have its original line endings in your working directory.`
```

 I guess it is good enough.

**Comment by r1chardj0n3s** [comment]
Yep, was nice and clean when I pulled master down a little while ago \o/

**Comment by dangillet** [comment]
Hello,

First of all, maybe I'm the culprit who added the CRLF in the repo. If that's the case, I apologise.

I'm afraid the new changes are not doing the proper thing. The `eol=lf` in the .gitattribute will **force** `LF` as line endings in the **working directory**, which is not what is desired.

What is desired is to have `LF` line endings in the **repository**. When checking out a commit in the working directory, git should adapt the line endings depending on the platform (keep `LF` on Linux, convert to `CRLF` on Windows). Then when committing a file, git normalizes the line endings converting them back to `LF` on Windows. Thus all line endings will be kept as `LF` in the repository.

For this to work, the .gitattribute should look like this I think:
```
*.anim -text
*.py text diff=python
*.txt text
*.rst text
```

I found some explanations in the documentation for .gitattribute [Checking-out and checking-in](https://git-scm.com/docs/gitattributes#_checking_out_and_checking_in).

What do you think ?

Dan

**Comment by ccanepa** [comment]
> First of all, maybe I'm the culprit who added the CRLF in the repo. If that's the case, I apologise.

Maybe I was, IDK; anyway the thing is to fix this going forward.

Followed the link you posted, I'm not sure if I understand exactly what it says.

I guess I need to see / know experimental results showing this works.

Something like create a repo, set the gitattributes on some canary files, change both eols in linux and windows, commit, checkout from the other OS to verify all is ok.

Maybe later today or tomorrow I  can do that; if you want to do it before, go ahead

**Comment by dangillet** [comment]
Github has a page dedicated to [line endings](https://help.github.com/articles/dealing-with-line-endings/) with a part on the [.gitaatributes](https://help.github.com/articles/dealing-with-line-endings/#per-repository-settings).

Otherwise here is a good article named [mind the end of your line](http://adaptivepatchwork.com/2012/03/01/mind-the-end-of-your-line/).

**Comment by ccanepa** [comment]
After reading trough the links you pasted I tough the modifications above should work, but testing seems to show different behavior than the expected: a fresh checkout on Windows shows LF eols for py, txt, rst; don't they be native, ie CRLF ?

Maybe my testing is at fault; I will recheck later, and see to complete the linux part.

For reference, I tested with https://github.com/ccanepa/giteol , the file results.txt there shows what is done and the results.

going to work, later...

**Comment by dangillet** [comment]
Hello Claudio,

Your tests work fine. The problem you seem to run into is that right after you commit on Windows, you don't see the *new* version. As explained in the Github page, after committing, you would need to do

```
# Remove every file from Git's index.
git rm --cached -r .
# Rewrite the Git index to pick up all the new line endings.
git reset --hard
```

And now you will see the line endings changes to `CRLF` on Windows.
When I pulled your repo, I saw immediately the correct line endings (`CRLF` in my case on Windows, except in `f.anim` where there were a mix).

**Comment by ccanepa** [comment]
Seems that my git thinks different.

In the WC 1, where the targets were created, committed and pushed

```
E:\_\cocos_pristine\giteol>git rm --cached -r .
rm '.gitattributes'
rm '.gitignore'
rm 'README.md'
rm 'a.py'
rm 'b.txt'
rm 'c.rst'
rm 'd.bat'
rm 'e.foo'
rm 'f.anim'
rm 'report_eols.py'
rm 'results.txt'
rm 'results_clean.txt'
rm 'rewrite_test_targets.py'

E:\_\cocos_pristine\giteol>git reset --hard
HEAD is now at d7aff27 updated report from a fresh clone in windows

E:\_\cocos_pristine\giteol>py -2.7 report_eols.py

OS: win
a.py: LF
b.txt: LF
c.rst: LF
d.bat: CRLF
e.foo: LF
f.anim: mixed
```

from the WC 2, a fresh clone from github

```
E:\_\cocos_pristine\giteol>py -2.7 report_eols.py

OS: win
a.py: LF
b.txt: LF
c.rst: LF
d.bat: CRLF
e.foo: LF
f.anim: mixed

E:\_\cocos_pristine\giteol>cd E:\_\cocos_pristine\giteol_2

E:\_\cocos_pristine\giteol_2>git rm --cached -r .
rm '.gitattributes'
rm '.gitignore'
rm 'README.md'
rm 'a.py'
rm 'b.txt'
rm 'c.rst'
rm 'd.bat'
rm 'e.foo'
rm 'f.anim'
rm 'report_eols.py'
rm 'results.txt'
rm 'results_clean.txt'
rm 'rewrite_test_targets.py'

E:\_\cocos_pristine\giteol_2>git reset --hard
HEAD is now at d7aff27 updated report from a fresh clone in windows

E:\_\cocos_pristine\giteol_2>py -2.7 report_eols.py

OS: win
a.py: LF
b.txt: LF
c.rst: LF
d.bat: CRLF
e.foo: LF
f.anim: mixed
```

Deleting both WC and cloning fresh gives the same result.

Maybe I need to update git; will see tomorrow

**Comment by ccanepa** [comment]
After updating git to 2.12.0 it worked on Windows.
Tested on linux (raspbian jessie), all ok.

Will merge now.
Thanks Daniel for looking at this.

**Comment by r1chardj0n3s** [comment]
Thanks for looking into this, sorry my first go at fixing it wasn't a great fix!

**Pull request merged**
