### PR TITLE
Fix compatibility with pyglet_ffmpeg2

### PR DESCRIPTION
**Pull request by chcarmen**
Since it has been already upgraded to pyglet_ffmpeg2, and it immediately loads ffmpeg on startup when executes import pyglet_ffmpeg2, so need to modify related code here in order to keep compatibility .

### CODE REVIEW

**Comment by ccanepa** [comment]
What is your OS ? I'm a little worried by two issues with tracebacks

- https://github.com/pythonarcade/pyglet-ffmpeg/issues/6
- https://github.com/pythonarcade/pyglet-ffmpeg/issues/5

The version released as pyglet_ffmpeg worked in my Windows testing; I will try to test with pyglet_ffmpef2

**Comment by chcarmen** [comment]
I am using Windows as well, pyglet_ffmpeg2 works for me, while the previous code using pyglet_ffmpeg doesn't work. since I intalled  pyglet_ffmpeg2 according to Cocos2d INSTALL file introduction.

**Comment by ccanepa** [comment]
working notes:
  - installing cocos but not ffmpeg gives a crash; should play normal even if silent

Details:

Setting the env:

```
	py -3.8 -m venv d:\dev\venvs\py38-cocos2020
	python -m pip install --upgrade pip

	python -m pip install numpy
	python -m pip install six
	python -m pip install pillow
	
	(py38-cocos2020) D:\dev>cd cocos2020

	(py38-cocos2020) D:\dev\cocos2020>git checkout -b chcarmen-master master
	Switched to a new branch 'chcarmen-master'

	(py38-cocos2020) D:\dev\cocos2020>git pull https://github.com/chcarmen/cocos.git
	 master
	remote: Enumerating objects: 5, done.
	remote: Counting objects: 100% (5/5), done.
	remote: Compressing objects: 100% (5/5), done.
	remote: Total 5 (delta 0), reused 0 (delta 0), pack-reused 0
	Unpacking objects: 100% (5/5), done.
	From https://github.com/chcarmen/cocos
	 * branch            master     -> FETCH_HEAD
	Updating fd9b960..1505548
	Fast-forward
	 samples/tetrico/soundex.py | 10 ++--------
	 1 file changed, 2 insertions(+), 8 deletions(-)

	(py38-cocos2020) D:\dev\cocos2020>git branch
	* chcarmen-master
	  master
	
	(py38-cocos2020) D:\dev\cocos2020>python -m pip install -e .
	Obtaining file:///D:/dev/cocos2020
	Requirement already satisfied: six>=1.4 in d:\dev\venvs\py38-cocos2020\lib\site-
	packages (from cocos2d==0.6.8) (1.13.0)
	Collecting pyglet<2,>=1.4.9
	  Downloading https://files.pythonhosted.org/packages/e7/a7/b609f0930b6e601b8f2f
	65636e5f652b5094e5faba0e44109e2a7edd7c3e/pyglet-1.4.9-py2.py3-none-any.whl (1.0M
	B)
		 |████████████████████████████████| 1.0MB 1.3MB/s
	Collecting future
	  Using cached https://files.pythonhosted.org/packages/45/0b/38b06fd9b92dc2b68d5
	8b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz
	Installing collected packages: future, pyglet, cocos2d
		Running setup.py install for future ... done
	  Running setup.py develop for cocos2d
	Successfully installed cocos2d future-0.18.2 pyglet-1.4.9

```
Running tetrico, expected normal play but silent, got crash at startup

```
(py38-cocos2020) D:\dev\cocos2020>cd D:\dev\cocos2020\samples\tetrico

(py38-cocos2020) D:\dev\cocos2020\samples\tetrico>python tetrico.py
warn; package pyglet_ffmpeg2 not found
Unexpected error loading library avutil-56: Could not find module 'avutil-56'. T
ry using the full path with constructor syntax.
Traceback (most recent call last):
  File "d:\dev\venvs\py38-cocos2020\lib\site-packages\pyglet\__init__.py", line
353, in __getattr__
    return getattr(self._module, name)
AttributeError: 'NoneType' object has no attribute 'codecs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tetrico.py", line 22, in <module>
    import soundex
  File "D:\dev\cocos2020\samples\tetrico\soundex.py", line 16, in <module>
    decoders = pyglet.media.codecs._decoder_extensions.get(".mp3", [])
  File "d:\dev\venvs\py38-cocos2020\lib\site-packages\pyglet\__init__.py", line
359, in __getattr__
    __import__(import_name)
  File "d:\dev\venvs\py38-cocos2020\lib\site-packages\pyglet\media\__init__.py",
 line 146, in <module>
    add_default_media_codecs()
  File "d:\dev\venvs\py38-cocos2020\lib\site-packages\pyglet\media\codecs\__init
__.py", line 164, in add_default_media_codecs
    if have_ffmpeg():
  File "d:\dev\venvs\py38-cocos2020\lib\site-packages\pyglet\media\codecs\__init
__.py", line 180, in have_ffmpeg
    from . import ffmpeg_lib
  File "d:\dev\venvs\py38-cocos2020\lib\site-packages\pyglet\media\codecs\ffmpeg
_lib\__init__.py", line 36, in <module>
    from .libavcodec import *
  File "d:\dev\venvs\py38-cocos2020\lib\site-packages\pyglet\media\codecs\ffmpeg
_lib\libavcodec.py", line 45, in <module>
    from . import libavutil
  File "d:\dev\venvs\py38-cocos2020\lib\site-packages\pyglet\media\codecs\ffmpeg
_lib\libavutil.py", line 46, in <module>
    avutil = pyglet.lib.load_library(
  File "d:\dev\venvs\py38-cocos2020\lib\site-packages\pyglet\lib.py", line 148,
in load_library
    lib = ctypes.cdll.LoadLibrary(name)
  File "D:\prog\Python38\lib\ctypes\__init__.py", line 447, in LoadLibrary
    return self._dlltype(name)
  File "D:\prog\Python38\lib\ctypes\__init__.py", line 369, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'avutil-56'. Try using the full path wi
th constructor syntax.
Unexpected error loading library avutil-56: Could not find module 'avutil-56'. T
ry using the full path with constructor syntax.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "d:\dev\venvs\py38-cocos2020\lib\site-packages\pyglet\media\__init__.py",
 line 146, in <module>
    add_default_media_codecs()
  File "d:\dev\venvs\py38-cocos2020\lib\site-packages\pyglet\media\codecs\__init
__.py", line 164, in add_default_media_codecs
    if have_ffmpeg():
  File "d:\dev\venvs\py38-cocos2020\lib\site-packages\pyglet\media\codecs\__init
__.py", line 180, in have_ffmpeg
    from . import ffmpeg_lib
  File "d:\dev\venvs\py38-cocos2020\lib\site-packages\pyglet\media\codecs\ffmpeg
_lib\__init__.py", line 36, in <module>
    from .libavcodec import *
  File "d:\dev\venvs\py38-cocos2020\lib\site-packages\pyglet\media\codecs\ffmpeg
_lib\libavcodec.py", line 45, in <module>
    from . import libavutil
  File "d:\dev\venvs\py38-cocos2020\lib\site-packages\pyglet\media\codecs\ffmpeg
_lib\libavutil.py", line 46, in <module>
    avutil = pyglet.lib.load_library(
  File "d:\dev\venvs\py38-cocos2020\lib\site-packages\pyglet\lib.py", line 148,
in load_library
    lib = ctypes.cdll.LoadLibrary(name)
  File "D:\prog\Python38\lib\ctypes\__init__.py", line 447, in LoadLibrary
    return self._dlltype(name)
  File "D:\prog\Python38\lib\ctypes\__init__.py", line 369, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'avutil-56'. Try using the full path wi
th constructor syntax.
```

Enough for today

**Comment by ccanepa** [comment]
pyglet has fixed the issue in the 1.4 maintenance branch, later I will advance with testing

**Comment by ccanepa** [comment]
Installing pyglet_ffmpeg2 tetrico plays with sounds.

Currently there's a stream of errors in the console, mostly from 
https://github.com/pyglet/pyglet/issues/123

Probably the ffmpeg part is working right, but I will wait until the directsound errors are fixed, to see if some ffmpef related errors are reported in console.

**Comment by ccanepa** [comment]
okay, seems clean.
I will merge now.

Thanks @chcarmen

**Pull request merged**
